  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume.pdf"

  [[main]]
  name = "Publications"
  weight = 400
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Projects"
  weight = 500
  identifier = "projects"
  url = "/projects/"

  [[main]]
  name = "Experience"
  weight = 600
  identifier = "experience"
  url = "/experience/"

  [[main]]
  name = "Contact"
  weight = 700
  identifier = "contact"
  url = "/contact/"
